# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [42]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [43]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 3. Reverse a vector (first element becomes last) 

In [44]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [45]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [46]:
x = [1, 2, 0, 0, 4, 0]
np.nonzero(x)

(array([0, 1, 4], dtype=int32),)

#### 6. Create a 3x3 identity matrix 

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 7. Create a 3x3x3 array with random values 

In [48]:
np.random.random((3,3,3))

array([[[0.53626322, 0.36055587, 0.06384344],
        [0.41125672, 0.18244906, 0.1346123 ],
        [0.88039722, 0.51814357, 0.49222565]],

       [[0.84473888, 0.64842228, 0.26519587],
        [0.89460441, 0.65617254, 0.31698405],
        [0.91248223, 0.6127556 , 0.98632587]],

       [[0.88704553, 0.51460121, 0.52893511],
        [0.63458646, 0.33515162, 0.45758909],
        [0.17132312, 0.96869237, 0.30821993]]])

#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [49]:
x = np.random.random((10,10))
print(np.min(x))
print(np.max(x))

0.010173804569565847
0.970940024745714


#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [50]:
a = np.array([[0,1],[1,0]])
print(a)
np.tile(a, (4,4))

[[0 1]
 [1 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [51]:
a = np.arange(15).reshape(5,3)
print(a)
b = np.arange(6).reshape(3,2)
print(b)
print(a.dot(b))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


In [52]:
x = np.arange(5)
np.tile(x, (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [53]:
x = np.zeros((5,5))
v = np.arange(5)
vv = x + v
print(vv)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 13. Create a random vector of size 10 and sort it 

In [55]:
x = np.random.random(10)
print(x)
print(np.sort(x))

[0.62600946 0.05939538 0.50155672 0.54239677 0.91054956 0.5345462
 0.07535004 0.14044128 0.80930272 0.43374708]
[0.05939538 0.07535004 0.14044128 0.43374708 0.50155672 0.5345462
 0.54239677 0.62600946 0.80930272 0.91054956]


#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [61]:
X = np.random.rand(5,10)

In [62]:
m = X - X.mean(axis=1).reshape(-1,1)
print(X.mean(axis=1).reshape(-1,1))
print(m)

[[0.51033774]
 [0.47726911]
 [0.45704607]
 [0.42543781]
 [0.43480895]]
[[ 0.29858711  0.46806422  0.16644135  0.02716212 -0.04415694 -0.30657921
   0.36769288 -0.3711189  -0.29700334 -0.30908929]
 [ 0.11407442 -0.02004881  0.48267208 -0.15969295  0.03829016 -0.10504722
  -0.18644356 -0.29063098  0.01629426  0.11053259]
 [-0.33036622 -0.09312883 -0.15668724 -0.30746661  0.17336288  0.23734444
   0.22973227  0.00993528 -0.18037808  0.41765211]
 [-0.0654691  -0.16991441 -0.38859121  0.52006169  0.45993005 -0.04557017
  -0.25582127  0.42642386 -0.41975124 -0.06129821]
 [ 0.09316775 -0.11317153  0.25022552  0.09417412 -0.1653655  -0.41188635
  -0.11905253  0.25422987  0.18378155 -0.06610289]]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [63]:
np.arange(1,11) * np.arange(1,11).reshape(10,1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [65]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
d = A.dot(B)
print(d)
print(np.diag(d))

[[0.41371477 1.11874582 1.57763764 0.80553433 1.26027528]
 [1.65502418 1.89795749 2.4322746  1.3661815  2.19161731]
 [1.13640413 1.03110814 1.81737972 1.04747916 1.83489569]
 [1.31150903 1.48938841 2.44314512 1.26229948 2.33595321]
 [0.64963319 1.29822503 2.05172789 1.23328414 1.71612104]]
[0.41371477 1.89795749 1.81737972 1.26229948 1.71612104]


In [66]:
print(np.diag(np.diag(d)))

[[0.41371477 0.         0.         0.         0.        ]
 [0.         1.89795749 0.         0.         0.        ]
 [0.         0.         1.81737972 0.         0.        ]
 [0.         0.         0.         1.26229948 0.        ]
 [0.         0.         0.         0.         1.71612104]]


#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [67]:
x = [1, 2, 3, 4, 5]
y = np.zeros(len(x) + (len(x)-1)*3)

y[::4] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [68]:
a = np.arange(25).reshape(5,5)

a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [69]:
Z = np.random.randint(0,10,50)
Z_bincount = np.bincount(Z)
print(Z_bincount)
print('The most frequent value is ', np.argmax(Z_bincount))

[7 7 2 6 5 5 1 3 9 5]
The most frequent value is  8


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [70]:
Z = np.arange(10000)
np.random.shuffle(Z)
print(Z)

n = 3
print (Z[np.argsort(Z)[-n:]])

[8262 6817 5185 ... 4560 9145 1687]
[9997 9998 9999]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [71]:
x = np.random.randint(1, 3, (10,3))
print(x)

[[2 2 2]
 [2 1 1]
 [2 2 2]
 [2 1 1]
 [1 1 1]
 [2 2 1]
 [2 1 1]
 [2 1 2]
 [2 2 2]
 [1 1 1]]


In [72]:
print(np.unique(x, axis=0))

[[1 1 1]
 [2 1 1]
 [2 1 2]
 [2 2 1]
 [2 2 2]]


#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [73]:
def moving_avg(arr, n):
    w = np.cumsum(arr)
    w[n:] = w[n:] - w[:-n]
    return w[(n-1):]/n

arr = np.arange(10)
np.random.shuffle(arr)
print(arr)
print(moving_avg(arr, 2))

[5 6 4 7 8 1 0 9 2 3]
[5.5 5.  5.5 7.5 4.5 0.5 4.5 5.5 2.5]


#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [76]:
a = np.random.rand(4,4)
idx = np.nonzero(a>0.5)
print([*zip(idx[0],idx[1])])

[(0, 0), (0, 3), (1, 3), (2, 1), (2, 2), (3, 2), (3, 3)]


#### 25. Write a function returning distance between two points

Test the function to check whether function is working correctly

Hint: There are two arguments of function indicating two points

In [77]:
def distance(point1, point2):
    dis = []
    for i in range(len(point1)):
        d = (point1[i] - point2[i])**2
        dis.append(d)
    return np.sqrt(sum(dis))

p1 = [2]
p2 = [5]
print(distance(p1,p2))

a = [1,2]
b = [2,4]
print(distance(a,b))

3.0
2.23606797749979


In [78]:
x = [1,2,3]
y = [4,5,6]
print(distance(x,y))

5.196152422706632
